import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding NGOs...");

  await prisma.ngo.createMany({
    data: [
      // PHILIPPINES - 20 NGOs
      {
        name: "Philippine Red Cross",
        location: "Manila, Philippines",
        country: "Philippines",
        description: "Leading humanitarian organization providing emergency response, blood services, and disaster relief across the Philippines.",
        score: 98,
        tags: "Emergency Response,Disaster Relief,Blood Services",
        latitude: 14.5995,
        longitude: 120.9842,
      },
      {
        name: "Caritas Manila",
        location: "Manila, Philippines",
        country: "Philippines",
        description: "Catholic social services organization supporting vulnerable communities through healthcare, education, and livelihood programs.",
        score: 92,
        tags: "Social Services,Healthcare,Education",
        latitude: 14.5995,
        longitude: 120.9842,
      },
      {
        name: "Gawad Kalinga",
        location: "Quezon City, Philippines",
        country: "Philippines",
        description: "Nationwide movement building sustainable communities and providing housing for the poor.",
        score: 95,
        tags: "Community Development,Housing,Sustainability",
        latitude: 14.6760,
        longitude: 121.0437,
      },
      {
        name: "Philippine Children's Medical Center",
        location: "Quezon City, Philippines",
        country: "Philippines",
        description: "Specialized pediatric hospital providing comprehensive healthcare for children nationwide.",
        score: 94,
        tags: "Pediatric Care,Children's Health",
        latitude: 14.6760,
        longitude: 121.0437,
      },
      {
        name: "World Vision Philippines",
        location: "Manila, Philippines",
        country: "Philippines",
        description: "Christian humanitarian organization working with children, families, and communities to overcome poverty and injustice.",
        score: 91,
        tags: "Child Welfare,Poverty Alleviation,Community Development",
        latitude: 14.5995,
        longitude: 120.9842,
      },
      {
        name: "Save the Children Philippines",
        location: "Makati, Philippines",
        country: "Philippines",
        description: "Leading independent organization creating lasting change for children in need in the Philippines and worldwide.",
        score: 93,
        tags: "Child Protection,Education,Emergency Response",
        latitude: 14.5547,
        longitude: 121.0244,
      },
      {
        name: "Plan International Philippines",
        location: "Makati, Philippines",
        country: "Philippines",
        description: "International development organization working to advance children's rights and equality for girls.",
        score: 89,
        tags: "Children's Rights,Gender Equality,Education",
        latitude: 14.5547,
        longitude: 121.0244,
      },
      {
        name: "CARE Philippines",
        location: "Manila, Philippines",
        country: "Philippines",
        description: "Fighting global poverty by empowering the most vulnerable, focusing on women and girls.",
        score: 88,
        tags: "Poverty Alleviation,Women's Empowerment",
        latitude: 14.5995,
        longitude: 120.9842,
      },
      {
        name: "Oxfam Philippines",
        location: "Quezon City, Philippines",
        country: "Philippines",
        description: "International confederation working to end poverty and injustice through advocacy and humanitarian work.",
        score: 87,
        tags: "Poverty Reduction,Human Rights,Advocacy",
        latitude: 14.6760,
        longitude: 121.0437,
      },
      {
        name: "UNICEF Philippines",
        location: "Manila, Philippines",
        country: "Philippines",
        description: "UN agency dedicated to protecting children's rights and helping meet their basic needs worldwide.",
        score: 96,
        tags: "Children's Rights,Humanitarian Aid,Education",
        latitude: 14.5995,
        longitude: 120.9842,
      },
      {
        name: "Philippine Animal Welfare Society",
        location: "Quezon City, Philippines",
        country: "Philippines",
        description: "Leading animal welfare organization in the Philippines providing rescue, rehabilitation, and education services.",
        score: 90,
        tags: "Animal Welfare,Rescue,Education",
        latitude: 14.6760,
        longitude: 121.0437,
      },
      {
        name: "Haribon Foundation",
        location: "Quezon City, Philippines",
        country: "Philippines",
        description: "Conservation organization protecting Philippine biodiversity and promoting sustainable development.",
        score: 85,
        tags: "Conservation,Biodiversity,Sustainable Development",
        latitude: 14.6760,
        longitude: 121.0437,
      },
      {
        name: "Lingkod Bayan",
        location: "Manila, Philippines",
        country: "Philippines",
        description: "Youth-led organization promoting volunteerism and community service among Filipino youth.",
        score: 82,
        tags: "Youth Volunteerism,Community Service,Education",
        latitude: 14.5995,
        longitude: 120.9842,
      },
      {
        name: "Bantay Bata",
        location: "Quezon City, Philippines",
        country: "Philippines",
        description: "Child rights organization working to protect Filipino children from abuse, exploitation, and violence.",
        score: 88,
        tags: "Child Protection,Human Rights,Advocacy",
        latitude: 14.6760,
        longitude: 121.0437,
      },
      {
        name: "Rise Against Hunger Philippines",
        location: "Manila, Philippines",
        country: "Philippines",
        description: "International organization fighting hunger through meal packaging events and sustainable food programs.",
        score: 86,
        tags: "Hunger Relief,Food Security,Sustainability",
        latitude: 14.5995,
        longitude: 120.9842,
      },
      {
        name: "ABS-CBN Foundation",
        location: "Quezon City, Philippines",
        country: "Philippines",
        description: "Social development arm of ABS-CBN providing education, health, and livelihood programs.",
        score: 84,
        tags: "Education,Health,Livelihood",
        latitude: 14.6760,
        longitude: 121.0437,
      },
      {
        name: "Tuloy Foundation",
        location: "Manila, Philippines",
        country: "Philippines",
        description: "Youth-led organization promoting volunteerism and nation-building through various social initiatives.",
        score: 81,
        tags: "Youth Leadership,Volunteerism,Social Initiatives",
        latitude: 14.5995,
        longitude: 120.9842,
      },
      {
        name: "Philippine Business for Social Progress",
        location: "Makati, Philippines",
        country: "Philippines",
        description: "Leading corporate citizenship organization promoting sustainable development through business.",
        score: 86,
        tags: "Corporate Social Responsibility,Sustainable Development,Business",
        latitude: 14.5547,
        longitude: 121.0244,
      },
      {
        name: "EduFuture Foundation",
        location: "Manila, Philippines",
        country: "Philippines",
        description: "Providing quality education and STEM programs for underprivileged youth.",
        score: 88,
        tags: "Education,STEM,Youth",
        latitude: 14.5995,
        longitude: 120.9842,
      },
      {
        name: "Philippine Rural Reconstruction Movement",
        location: "Quezon City, Philippines",
        country: "Philippines",
        description: "Grassroots organization working for sustainable rural development and social justice.",
        score: 83,
        tags: "Rural Development,Social Justice,Sustainability",
        latitude: 14.6760,
        longitude: 121.0437,
      },

      // UNITED STATES - 20 NGOs
      {
        name: "Partners In Health",
        location: "Boston, USA",
        country: "United States",
        description: "Global health organization bringing the benefits of modern medical science to those most in need.",
        score: 94,
        tags: "Global Health,Medical Care,Community Health",
        latitude: 42.3601,
        longitude: -71.0589,
      },
      {
        name: "PATH",
        location: "Seattle, USA",
        country: "United States",
        description: "Global health organization working to accelerate health equity by bringing together public institutions, businesses, social enterprises.",
        score: 91,
        tags: "Global Health,Vaccines,Health Equity",
        latitude: 47.6062,
        longitude: -122.3321,
      },
      {
        name: "Helen Keller International",
        location: "New York, USA",
        country: "United States",
        description: "Fighting and treating preventable blindness and malnutrition through health, nutrition, and education programs.",
        score: 89,
        tags: "Nutrition,Eye Health,Vitamin A Deficiency",
        latitude: 40.7128,
        longitude: -74.0060,
      },
      {
        name: "The Nature Conservancy",
        location: "Arlington, USA",
        country: "United States",
        description: "Environmental nonprofit working to create a world where people and nature can thrive by protecting lands and waters.",
        score: 88,
        tags: "Conservation,Land Protection,Water Resources",
        latitude: 38.8790,
        longitude: -77.1068,
      },
      {
        name: "Room to Read",
        location: "San Francisco, USA",
        country: "United States",
        description: "Global organization transforming the lives of millions of children in low-income communities by focusing on literacy and gender equality in education.",
        score: 92,
        tags: "Literacy,Education,Gender Equality",
        latitude: 37.7749,
        longitude: -122.4194,
      },
      {
        name: "Teach For All",
        location: "New York, USA",
        country: "United States",
        description: "Global network of independent organizations working to expand educational opportunity in their countries.",
        score: 87,
        tags: "Education,Teacher Training,Educational Equity",
        latitude: 40.7128,
        longitude: -74.0060,
      },
      {
        name: "International Fund for Animal Welfare",
        location: "Yarmouth Port, USA",
        country: "United States",
        description: "Global animal welfare and conservation charity working to rescue and protect animals around the world.",
        score: 86,
        tags: "Animal Rescue,Conservation,Wildlife Protection",
        latitude: 41.7057,
        longitude: -70.2495,
      },
      {
        name: "Human Rights Watch",
        location: "New York, USA",
        country: "United States",
        description: "Independent organization conducting research and advocacy on human rights.",
        score: 92,
        tags: "Human Rights,Research,Advocacy",
        latitude: 40.7128,
        longitude: -74.0060,
      },
      {
        name: "Catholic Relief Services",
        location: "Baltimore, USA",
        country: "United States",
        description: "International humanitarian agency assisting the poor and vulnerable overseas.",
        score: 91,
        tags: "Humanitarian Aid,Poverty Relief,Development",
        latitude: 39.2904,
        longitude: -76.6122,
      },
      {
        name: "Mercy Corps",
        location: "Portland, USA",
        country: "United States",
        description: "Global humanitarian organization helping people survive and thrive in crisis.",
        score: 89,
        tags: "Humanitarian Aid,Crisis Response,Development",
        latitude: 45.5152,
        longitude: -122.6784,
      },
      {
        name: "International Rescue Committee",
        location: "New York, USA",
        country: "United States",
        description: "Humanitarian nonprofit providing lifesaving care and life-changing assistance to refugees.",
        score: 90,
        tags: "Refugee Aid,Humanitarian Care,Resettlement",
        latitude: 40.7128,
        longitude: -74.0060,
      },
      {
        name: "Direct Relief",
        location: "Santa Barbara, USA",
        country: "United States",
        description: "Humanitarian aid organization providing medical assistance and supplies to health programs worldwide.",
        score: 88,
        tags: "Medical Aid,Humanitarian Supplies,Health Programs",
        latitude: 34.4208,
        longitude: -119.6982,
      },
      {
        name: "Project HOPE",
        location: "Millwood, USA",
        country: "United States",
        description: "Health education and humanitarian assistance organization working in more than 30 countries.",
        score: 87,
        tags: "Health Education,Humanitarian Aid,Medical Training",
        latitude: 37.0902,
        longitude: -95.7129,
      },
      {
        name: "United Nations Development Programme (UNDP)",
        location: "New York, USA",
        country: "United States",
        description: "UN agency supporting countries in achieving the Sustainable Development Goals.",
        score: 95,
        tags: "Sustainable Development,Poverty Reduction,Climate Action",
        latitude: 40.7128,
        longitude: -74.0060,
      },
      {
        name: "Accessible Technology Initiative",
        location: "San Francisco, USA",
        country: "United States",
        description: "Developing assistive technologies for people with disabilities.",
        score: 77,
        tags: "Assistive Technology,Accessibility",
        latitude: 37.7749,
        longitude: -122.4194,
      },
      {
        name: "Tech for Humanity",
        location: "Silicon Valley, USA",
        country: "United States",
        description: "Leveraging technology to solve social and environmental challenges.",
        score: 86,
        tags: "Technology,Social Innovation",
        latitude: 37.4419,
        longitude: -122.1430,
      },
      {
        name: "Plastic Pollution Solutions",
        location: "Honolulu, Hawaii, USA",
        country: "United States",
        description: "Ocean plastic cleanup and plastic pollution prevention programs.",
        score: 81,
        tags: "Plastic Pollution,Ocean Cleanup",
        latitude: 21.3099,
        longitude: -157.8581,
      },
      {
        name: "Save the Children US",
        location: "Fairfield, USA",
        country: "United States",
        description: "Leading independent organization creating lasting change for children in need worldwide.",
        score: 93,
        tags: "Child Protection,Education,Emergency Response",
        latitude: 41.1408,
        longitude: -73.2613,
      },
      {
        name: "CARE International US",
        location: "Atlanta, USA",
        country: "United States",
        description: "Fighting global poverty by empowering the most vulnerable, focusing on women and girls.",
        score: 88,
        tags: "Poverty Alleviation,Women's Empowerment",
        latitude: 33.7490,
        longitude: -84.3880,
      },
      {
        name: "World Vision US",
        location: "Federal Way, USA",
        country: "United States",
        description: "Christian humanitarian organization working with children, families, and communities to overcome poverty and injustice.",
        score: 91,
        tags: "Child Welfare,Poverty Alleviation,Community Development",
        latitude: 47.3223,
        longitude: -122.3126,
      },

      // UNITED KINGDOM - 20 NGOs
      {
        name: "Amnesty International",
        location: "London, UK",
        country: "United Kingdom",
        description: "Global movement of more than 10 million people in over 150 countries campaigning for human rights.",
        score: 94,
        tags: "Human Rights,Justice,Advocacy",
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        name: "World Animal Protection",
        location: "London, UK",
        country: "United Kingdom",
        description: "Animal welfare organization working to create a better world for animals through campaigning and education.",
        score: 85,
        tags: "Animal Welfare,Animal Protection,Education",
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        name: "Malaria Consortium",
        location: "London, UK",
        country: "United Kingdom",
        description: "Global organization dedicated to the control and elimination of malaria and other communicable diseases.",
        score: 89,
        tags: "Malaria Control,Disease Prevention,Global Health",
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        name: "Sightsavers",
        location: "Haywards Heath, UK",
        country: "United Kingdom",
        description: "International organization working to prevent avoidable blindness and promote equality for people with disabilities.",
        score: 87,
        tags: "Eye Health,Disability Rights,Equality",
        latitude: 51.0074,
        longitude: -0.1278,
      },
      {
        name: "Oxfam GB",
        location: "Oxford, UK",
        country: "United Kingdom",
        description: "International confederation working to end poverty and injustice through advocacy and humanitarian work.",
        score: 87,
        tags: "Poverty Reduction,Human Rights,Advocacy",
        latitude: 51.7520,
        longitude: -1.2577,
      },
      {
        name: "Save the Children UK",
        location: "London, UK",
        country: "United Kingdom",
        description: "Leading independent organization creating lasting change for children in need worldwide.",
        score: 93,
        tags: "Child Protection,Education,Emergency Response",
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        name: "Christian Aid",
        location: "London, UK",
        country: "United Kingdom",
        description: "Christian organization working globally for an end to poverty and its causes.",
        score: 86,
        tags: "Christian Aid,Poverty Relief,Development",
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        name: "ActionAid UK",
        location: "London, UK",
        country: "United Kingdom",
        description: "International development organization working against poverty and injustice worldwide.",
        score: 88,
        tags: "Poverty Reduction,Human Rights,Women's Rights",
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        name: "Plan International UK",
        location: "Woking, UK",
        country: "United Kingdom",
        description: "International development organization working to advance children's rights and equality for girls.",
        score: 89,
        tags: "Children's Rights,Gender Equality,Education",
        latitude: 51.3180,
        longitude: -0.5569,
      },
      {
        name: "WaterAid UK",
        location: "London, UK",
        country: "United Kingdom",
        description: "International organization transforming lives by improving access to safe water, hygiene and sanitation.",
        score: 90,
        tags: "Water,Sanitation,Hygiene",
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        name: "Tearfund",
        location: "Middlesbrough, UK",
        country: "United Kingdom",
        description: "Christian relief and development organization working to end poverty and injustice worldwide.",
        score: 85,
        tags: "Christian Aid,Poverty Relief,Development",
        latitude: 54.5742,
        longitude: -1.2344,
      },
      {
        name: "Concern Worldwide UK",
        location: "London, UK",
        country: "United Kingdom",
        description: "Humanitarian organization working to save and change lives in the world's poorest communities.",
        score: 87,
        tags: "Humanitarian Aid,Poverty Relief,Emergency Response",
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        name: "Islamic Relief UK",
        location: "Birmingham, UK",
        country: "United Kingdom",
        description: "International humanitarian organization providing relief and development assistance worldwide.",
        score: 84,
        tags: "Humanitarian Aid,Islamic Relief,Development",
        latitude: 52.4862,
        longitude: -1.8904,
      },
      {
        name: "British Red Cross",
        location: "London, UK",
        country: "United Kingdom",
        description: "Humanitarian organization providing emergency response and support services across the UK and internationally.",
        score: 91,
        tags: "Emergency Response,Humanitarian Aid,First Aid",
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        name: "RSPCA",
        location: "Horsham, UK",
        country: "United Kingdom",
        description: "Animal welfare charity working to protect animals and end animal cruelty.",
        score: 88,
        tags: "Animal Welfare,Animal Protection,Cruelty Prevention",
        latitude: 51.0629,
        longitude: -0.3258,
      },
      {
        name: "WWF-UK",
        location: "Woking, UK",
        country: "United Kingdom",
        description: "Environmental charity working to protect the planet and build a sustainable future.",
        score: 89,
        tags: "Conservation,Environment,Climate Change",
        latitude: 51.3180,
        longitude: -0.5569,
      },
      {
        name: "Friends of the Earth UK",
        location: "London, UK",
        country: "United Kingdom",
        description: "Environmental campaigning organization working for a sustainable future.",
        score: 83,
        tags: "Environmental Activism,Sustainability,Campaigning",
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        name: "Greenpeace UK",
        location: "London, UK",
        country: "United Kingdom",
        description: "Independent global campaigning network that acts to change attitudes and behavior to protect the environment.",
        score: 90,
        tags: "Environmental Activism,Climate Action,Ocean Conservation",
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        name: "The Children's Society",
        location: "London, UK",
        country: "United Kingdom",
        description: "Children's charity working to create a better world for children and young people.",
        score: 86,
        tags: "Child Welfare,Youth Support,Children's Rights",
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        name: "Shelter UK",
        location: "London, UK",
        country: "United Kingdom",
        description: "Housing charity working to end homelessness and bad housing in England and Scotland.",
        score: 85,
        tags: "Housing,Homelessness,Social Justice",
        latitude: 51.5074,
        longitude: -0.1278,
      },

      // SWITZERLAND - 20 NGOs
      {
        name: "Doctors Without Borders (MSF)",
        location: "Geneva, Switzerland",
        country: "Switzerland",
        description: "International medical humanitarian organization providing emergency medical assistance to people affected by conflict, epidemics, disasters.",
        score: 97,
        tags: "Emergency Medicine,Humanitarian Aid,Global Health",
        latitude: 46.2044,
        longitude: 6.1432,
      },
      {
        name: "International Committee of the Red Cross",
        location: "Geneva, Switzerland",
        country: "Switzerland",
        description: "Humanitarian institution providing protection and assistance to victims of war and armed violence.",
        score: 96,
        tags: "Humanitarian Law,War Victims,Protection",
        latitude: 46.2044,
        longitude: 6.1432,
      },
      {
        name: "World Wildlife Fund (WWF)",
        location: "Gland, Switzerland",
        country: "Switzerland",
        description: "International organization working on issues regarding the conservation, research and restoration of the environment.",
        score: 93,
        tags: "Conservation,Environment,Climate Change",
        latitude: 46.4207,
        longitude: 6.2724,
      },
      {
        name: "World Health Organization (WHO)",
        location: "Geneva, Switzerland",
        country: "Switzerland",
        description: "UN specialized agency directing and coordinating international health work.",
        score: 97,
        tags: "Global Health,Disease Prevention,Health Policy",
        latitude: 46.2044,
        longitude: 6.1432,
      },
      {
        name: "International Labour Organization (ILO)",
        location: "Geneva, Switzerland",
        country: "Switzerland",
        description: "UN agency promoting social justice and internationally recognized human and labour rights.",
        score: 92,
        tags: "Labour Rights,Social Justice,Human Rights",
        latitude: 46.2044,
        longitude: 6.1432,
      },
      {
        name: "United Nations High Commissioner for Refugees (UNHCR)",
        location: "Geneva, Switzerland",
        country: "Switzerland",
        description: "UN agency protecting and supporting refugees and displaced persons worldwide.",
        score: 95,
        tags: "Refugee Protection,Humanitarian Aid,Displacement",
        latitude: 46.2044,
        longitude: 6.1432,
      },
      {
        name: "World Economic Forum",
        location: "Geneva, Switzerland",
        country: "Switzerland",
        description: "International organization for public-private cooperation working to improve the state of the world.",
        score: 88,
        tags: "Global Cooperation,Economic Development,Sustainability",
        latitude: 46.2044,
        longitude: 6.1432,
      },
      {
        name: "Caritas Switzerland",
        location: "Lucerne, Switzerland",
        country: "Switzerland",
        description: "Catholic social services organization providing humanitarian aid and development assistance worldwide.",
        score: 87,
        tags: "Humanitarian Aid,Social Services,Development",
        latitude: 47.0502,
        longitude: 8.3093,
      },
      {
        name: "Swiss Red Cross",
        location: "Bern, Switzerland",
        country: "Switzerland",
        description: "Swiss humanitarian organization providing emergency response and humanitarian aid worldwide.",
        score: 90,
        tags: "Emergency Response,Humanitarian Aid,First Aid",
        latitude: 46.9481,
        longitude: 7.4474,
      },
      {
        name: "HEKS/EPER",
        location: "Zurich, Switzerland",
        country: "Switzerland",
        description: "Protestant development organization working for a just and sustainable world.",
        score: 85,
        tags: "Development,Sustainability,Social Justice",
        latitude: 47.3769,
        longitude: 8.5417,
      },
      {
        name: "Terre des Hommes Switzerland",
        location: "Lausanne, Switzerland",
        country: "Switzerland",
        description: "Children's rights organization working to improve the lives of children worldwide.",
        score: 86,
        tags: "Children's Rights,Child Protection,Development",
        latitude: 46.5197,
        longitude: 6.6323,
      },
      {
        name: "Solidar Suisse",
        location: "Zurich, Switzerland",
        country: "Switzerland",
        description: "Swiss development organization working for sustainable development and poverty reduction.",
        score: 83,
        tags: "Sustainable Development,Poverty Reduction,International Cooperation",
        latitude: 47.3769,
        longitude: 8.5417,
      },
      {
        name: "Bread for All",
        location: "Bern, Switzerland",
        country: "Switzerland",
        description: "Swiss development organization working for fair trade and sustainable development.",
        score: 82,
        tags: "Fair Trade,Sustainable Development,Global Justice",
        latitude: 46.9481,
        longitude: 7.4474,
      },
      {
        name: "Swisspeace",
        location: "Bern, Switzerland",
        country: "Switzerland",
        description: "Swiss peace research institute working on conflict prevention and peacebuilding.",
        score: 81,
        tags: "Peace Research,Conflict Prevention,Peacebuilding",
        latitude: 46.9481,
        longitude: 7.4474,
      },
      {
        name: "Alliance Sud",
        location: "Bern, Switzerland",
        country: "Switzerland",
        description: "Swiss alliance of development organizations working for global justice and sustainable development.",
        score: 84,
        tags: "Global Justice,Sustainable Development,Development Cooperation",
        latitude: 46.9481,
        longitude: 7.4474,
      },
      {
        name: "Fastenopfer",
        location: "Bern, Switzerland",
        country: "Switzerland",
        description: "Swiss Catholic Lenten Fund supporting development projects worldwide.",
        score: 80,
        tags: "Development Aid,Catholic Aid,International Solidarity",
        latitude: 46.9481,
        longitude: 7.4474,
      },
      {
        name: "Mission 21",
        location: "Basel, Switzerland",
        country: "Switzerland",
        description: "Swiss mission organization working for justice, peace and integrity of creation.",
        score: 79,
        tags: "Mission Work,Peace,Environmental Justice",
        latitude: 47.5596,
        longitude: 7.5886,
      },
      {
        name: "Swissaid",
        location: "Bern, Switzerland",
        country: "Switzerland",
        description: "Swiss development organization working for fair economic relations and sustainable development.",
        score: 83,
        tags: "Fair Trade,Sustainable Development,Economic Justice",
        latitude: 46.9481,
        longitude: 7.4474,
      },
      {
        name: "Enfants du Monde",
        location: "Geneva, Switzerland",
        country: "Switzerland",
        description: "Swiss organization working to protect and promote children's rights worldwide.",
        score: 85,
        tags: "Children's Rights,Child Protection,Education",
        latitude: 46.2044,
        longitude: 6.1432,
      },
      {
        name: "Pro Natura",
        location: "Basel, Switzerland",
        country: "Switzerland",
        description: "Swiss nature conservation organization protecting biodiversity and natural habitats.",
        score: 87,
        tags: "Nature Conservation,Biodiversity,Environmental Protection",
        latitude: 47.5596,
        longitude: 7.5886,
      },

      // NETHERLANDS - 20 NGOs
      {
        name: "Greenpeace International",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Independent global campaigning network that acts to change attitudes and behavior, to protect and conserve the environment.",
        score: 90,
        tags: "Environmental Activism,Climate Action,Ocean Conservation",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "Oxfam Novib",
        location: "The Hague, Netherlands",
        country: "Netherlands",
        description: "Dutch development organization working to end poverty and injustice worldwide.",
        score: 87,
        tags: "Poverty Reduction,Human Rights,Development",
        latitude: 52.0705,
        longitude: 4.3007,
      },
      {
        name: "Plan Netherlands",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch branch of Plan International working to advance children's rights and equality for girls.",
        score: 89,
        tags: "Children's Rights,Gender Equality,Education",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "Save the Children Netherlands",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch branch of Save the Children creating lasting change for children in need worldwide.",
        score: 93,
        tags: "Child Protection,Education,Emergency Response",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "CARE Netherlands",
        location: "The Hague, Netherlands",
        country: "Netherlands",
        description: "Dutch branch of CARE fighting global poverty by empowering the most vulnerable.",
        score: 88,
        tags: "Poverty Alleviation,Women's Empowerment",
        latitude: 52.0705,
        longitude: 4.3007,
      },
      {
        name: "World Vision Netherlands",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch branch of World Vision working with children, families, and communities to overcome poverty.",
        score: 91,
        tags: "Child Welfare,Poverty Alleviation,Community Development",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "Amnesty International Netherlands",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch branch of Amnesty International campaigning for human rights worldwide.",
        score: 94,
        tags: "Human Rights,Justice,Advocacy",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "Dutch Red Cross",
        location: "The Hague, Netherlands",
        country: "Netherlands",
        description: "Dutch humanitarian organization providing emergency response and humanitarian aid worldwide.",
        score: 90,
        tags: "Emergency Response,Humanitarian Aid,First Aid",
        latitude: 52.0705,
        longitude: 4.3007,
      },
      {
        name: "Cordaid",
        location: "The Hague, Netherlands",
        country: "Netherlands",
        description: "Dutch Catholic development organization working for a just and sustainable world.",
        score: 86,
        tags: "Development,Sustainability,Social Justice",
        latitude: 52.0705,
        longitude: 4.3007,
      },
      {
        name: "Hivos",
        location: "The Hague, Netherlands",
        country: "Netherlands",
        description: "Dutch development organization working for a more just and sustainable world.",
        score: 85,
        tags: "Sustainable Development,Social Justice,Innovation",
        latitude: 52.0705,
        longitude: 4.3007,
      },
      {
        name: "Stichting Vluchteling",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch refugee organization working to improve the position of refugees and asylum seekers.",
        score: 84,
        tags: "Refugee Support,Asylum Seekers,Human Rights",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "Terre des Hommes Netherlands",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch children's rights organization working to improve the lives of children worldwide.",
        score: 86,
        tags: "Children's Rights,Child Protection,Development",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "Both ENDS",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch organization working for sustainable development and fair international relations.",
        score: 83,
        tags: "Sustainable Development,Fair Trade,International Relations",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "Milieudefensie",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch environmental organization working for a sustainable and fair world.",
        score: 87,
        tags: "Environmental Protection,Sustainability,Climate Action",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "Stichting Natuurmonumenten",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch nature conservation organization protecting natural heritage and biodiversity.",
        score: 88,
        tags: "Nature Conservation,Biodiversity,Environmental Protection",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "War Child Netherlands",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch organization helping children affected by war and armed conflict worldwide.",
        score: 89,
        tags: "Child Protection,War Victims,Humanitarian Aid",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "Women Win",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch organization working to advance gender equality through sport and play.",
        score: 82,
        tags: "Gender Equality,Women's Empowerment,Sport",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "Fairtrade Netherlands",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch organization promoting fair trade and sustainable development worldwide.",
        score: 81,
        tags: "Fair Trade,Sustainable Development,Trade Justice",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "Stichting Kinderpostzegels Nederland",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch children's charity working to improve the lives of children worldwide.",
        score: 85,
        tags: "Children's Charity,Child Welfare,Education",
        latitude: 52.3676,
        longitude: 4.9041,
      },
      {
        name: "SPARK",
        location: "Amsterdam, Netherlands",
        country: "Netherlands",
        description: "Dutch organization working to end child sexual exploitation and trafficking.",
        score: 87,
        tags: "Child Protection,Anti-Trafficking,Human Rights",
        latitude: 52.3676,
        longitude: 4.9041,
      },
    ],
  });

  console.log("Seed complete.");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
